name: Node.js CI

on:
  schedule:
    #- cron: '0 0 1 * *'  # every first day of the month
    - cron: '*/5 * * * *'  # every 5 mins

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 14.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: node dist
