name: Schedule bot monthly

on:
  push:
    branches: [master]
  schedule:
    #- cron: '0 0 1 * *'  # every first day of the month
    - cron: '*/2 * * * *'  # every 5 mins

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment:
      name: Production

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        WHITELIST_GIST_ID: ${{ secrets.WHITELIST_GIST_ID }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    - run: npm ci
    - run: npm run build
    - run: node dist
